[mongodb]
mongodb.devops2025.shop ansible_user=ec2-user ansible_password=DevOps321

[catalogue]
catalogue.devops2025.shop ansible_user=ec2-user ansible_password=DevOps321

[redis]
redis.devops2025.shop ansible_user=ec2-user ansible_password=DevOps321

[user]
user.devops2025.shop ansible_user=ec2-user ansible_password=DevOps321

[cart]
cart.devops2025.shop ansible_user=ec2-user ansible_password=DevOps321

[frontend]
frontend.devops2025.shop ansible_user=ec2-user ansible_password=DevOps321

[mysql]
mysql.devops2025.shop ansible_user=ec2-user ansible_password=DevOps321

[shipping]
shipping.devops2025.shop ansible_user=ec2-user ansible_password=DevOps321

[rabbitmq]
rabbitmq.devops2025.shop ansible_user=ec2-user ansible_password=DevOps321

[payment]
payment.devops2025.shop ansible_user=ec2-user ansible_password=DevOps321